sampler MainTexture : register(s0);
sampler lutTex : register(s1);

float lutSize = 32.0;
float offset = 1.0 / 64.0;
float scale = 31.0 / 32.0;


float4 LUT_ps(float2 iTexCoord : TEXCOORD0) : COLOR
{
	float4 rawCol = tex2D(MainTexture, iTexCoord);

	float4 col = rawCol;
	col.rgb = tex3D(lutTex, scale * rawCol.rgb + offset);

	return col;
}

float4 Invert_ps (float2 iTexCoord : TEXCOORD0) : COLOR
{
	float4 col = tex2D(MainTexture, iTexCoord);
	return 1 - col;
}
